---
- hosts: 127.0.0.1
  become: true
  gather_facts: true
  tasks:
  - name: run openshift prerequirements
    command: ansible-playbook -vvv  -i /root/inventory openshift-ansible/playbooks/prerequisites.yml
  - name: run openshift deploy
    command: ansible-playbook -vvv  -i /root/inventory openshift-ansible/playbooks/deploy_cluster.yml

  - name: Test jinja2template
    template: src=ldapjinja2.j2 dest=/etc/master-config.yml

